### PR TITLE
add semaphore example

### PR DESCRIPTION
**Pull request by LittleCube-hax**
I tried to copy your exact style so it would fit in with the rest of the repo. This is just one small example of why semaphores are useful, and it may be a really good foundation down the line for the more complex semaphore problems.

Notice I use the cpp thread library, which is normally frowned upon by cpplint (the Chromium team people are weird). I also named the semaphore wrapper class the way I did because I accidentally named the header semaphore.h, which can't work, but I still wanted to make the semaphore code in main easier to read.

Let me know if you want me to make any additional changes.

### CODE REVIEW

**Comment by lewisjs4** [comment]
There is a merge conflict.

Please create a directory named student_submissions and move your code into this directory. As long as it is not the solution to projects, I think it will be interesting to see what code we can accumulate.

**Comment by LittleCube-hax** [comment]
Done. I also took the liberty of showing the fork name change in the README as well.

**Comment by LittleCube-hax** [comment]
I believe this pull request is ready to merged, unless there is anything here that you'd even remotely like me to change.

**Comment by LittleCube-hax** [comment]
...starting now.

**Review by lewisjs4 — APPROVED** [review]
This all seems fine. The subdir means conflicts are not possible. Thank you for updating the readme. I NEED to get better about that.

From now on, any commit you make to these files, I will blanket approve. Worst case is a rollback, right? That is cheap in git.

**Pull request merged**
